import Mathlib

/-!
# UC-001 WP07: functional-preorder bridge

This module keeps functional-preorder downward closure distinct from the
subset-downward predicate used by the WP06 ideal-family bridge.

The definitions below mirror the semantic surface audited in
`kashiwabarakenji/avg-rare` without importing that repository as a trusted
Lean dependency.
-/

namespace MathSolve.UnionClosed.WP07

open Finset
open scoped BigOperators

universe u

variable {α : Type u} [DecidableEq α]

/-- The finite-family representation used by the governed UC development. -/
abbrev Family (α : Type u) [DecidableEq α] := Finset (Finset α)

/-- WP06's subset-downward local ideal-family predicate, reproduced here only
so the semantic non-implication can be stated inside MATHSOLVE. -/
def IsIdealFamilyOn (F : Family α) (U : Finset α) : Prop :=
  (∀ S ∈ F, S ⊆ U) ∧
  (∅ : Finset α) ∈ F ∧
  U ∈ F ∧
  U.Nonempty ∧
  ∀ {A B : Finset α}, B ∈ F → B ≠ U → A ⊆ B → A ∈ F

/-- Local average-rarity statement in the same finite-family vocabulary used by
WP06/MATHCERT. -/
def IsAverageRareOn (F : Family α) (U : Finset α) : Prop :=
  2 * (F.sum fun S => S.card) ≤ U.card * F.card

/-- Source-shaped functional-preorder datum. This matches the audited upstream
`FuncSetup`: a finite nonempty ground and a self-map of its subtype. -/
structure FuncSetup (α : Type u) [DecidableEq α] where
  ground : Finset α
  nonempty : Nonempty ground
  f : {x // x ∈ ground} → {y // y ∈ ground}

namespace FuncSetup

variable (S : FuncSetup α)

abbrev Elem := {x : α // x ∈ S.ground}

/-- One functional edge. -/
def cover (x y : S.Elem) : Prop := S.f x = y

/-- Reflexive-transitive reachability generated by the functional edges. -/
def le (x y : S.Elem) : Prop := Relation.ReflTransGen S.cover x y

/-- Reachability stated on ambient elements with explicit ground witnesses. -/
def leOn (y x : α) : Prop :=
  ∃ (hy : y ∈ S.ground) (hx : x ∈ S.ground),
    S.le ⟨y, hy⟩ ⟨x, hx⟩

/-- The audited upstream order-ideal predicate. -/
def IsOrderIdealOn (I : Finset α) : Prop :=
  I ⊆ S.ground ∧
    ∀ ⦃x⦄, x ∈ I → ∀ ⦃y⦄, y ∈ S.ground → S.leOn y x → y ∈ I

/-- The finite family of all preorder order ideals. This is the local
`Family α` realization of the upstream source-shaped `idealFamily.edgeFinset`. -/
noncomputable def idealFamily : Family α := by
  classical
  exact S.ground.powerset.filter (fun I => decide (S.IsOrderIdealOn I))

@[simp] theorem mem_idealFamily_iff {I : Finset α} :
    I ∈ S.idealFamily ↔ S.IsOrderIdealOn I := by
  classical
  simp [idealFamily, IsOrderIdealOn]

/-- Any functional-preorder ideal-family member lies inside its ground. -/
theorem member_subset_ground {I : Finset α} (hI : I ∈ S.idealFamily) :
    I ⊆ S.ground :=
  ((S.mem_idealFamily_iff).mp hI).1

end FuncSetup

/-- The exact D003 local predicate: the ground is explicit, the self-map is
carried by a source-shaped `FuncSetup`, and family equality is extensional and
explicit. -/
def IsFunctionalPreorderIdealFamilyOn (F : Family α) (U : Finset α) : Prop :=
  ∃ S : FuncSetup α, S.ground = U ∧ F = S.idealFamily

/-- D003 exposes the carrier discipline needed by the later average-rarity
bridge. -/
theorem functionalPreorderIdealFamily_members_subset
    {F : Family α} {U : Finset α}
    (h : IsFunctionalPreorderIdealFamilyOn F U) :
    ∀ I ∈ F, I ⊆ U := by
  rcases h with ⟨S, hU, hF⟩
  intro I hI
  rw [hF] at hI
  rw [← hU]
  exact S.member_subset_ground hI

/-! ## D002: exact three-element semantic obstruction -/

inductive Chain3
  | a
  | b
  | c
  deriving DecidableEq, Fintype

namespace Chain3

/-- Rank along the chain `a < b < c`. -/
def rank : Chain3 → Nat
  | a => 0
  | b => 1
  | c => 2

/-- The requested functional chain: `a ↦ b`, `b ↦ c`, `c ↦ c`. -/
def rawNext : Chain3 → Chain3
  | a => b
  | b => c
  | c => c

abbrev ground : Finset Chain3 := Finset.univ

def next (x : {x // x ∈ ground}) : {x // x ∈ ground} :=
  ⟨rawNext x.1, by simp [ground]⟩

theorem rank_le_rank_rawNext (x : Chain3) : rank x ≤ rank (rawNext x) := by
  cases x <;> decide

end Chain3

/-- Source-shaped `FuncSetup` for the three-element chain. -/
def chainSetup : FuncSetup Chain3 :=
  { ground := Chain3.ground
    nonempty := ⟨⟨Chain3.a, by simp [Chain3.ground]⟩⟩
    f := Chain3.next }

abbrev chainA : Finset Chain3 := {Chain3.b}
abbrev chainB : Finset Chain3 := {Chain3.a, Chain3.b}
abbrev chainExpectedFamily : Family Chain3 :=
  {∅, {Chain3.a}, chainB, Chain3.ground}

/-- A one-step functional edge never decreases chain rank. -/
theorem chain_cover_rank_mono {x y : chainSetup.Elem}
    (h : chainSetup.cover x y) :
    Chain3.rank x.1 ≤ Chain3.rank y.1 := by
  unfold FuncSetup.cover at h
  change Chain3.next x = y at h
  subst y
  simpa [Chain3.next] using Chain3.rank_le_rank_rawNext x.1

/-- Reachability in the functional preorder never decreases chain rank. -/
theorem chain_le_rank_mono {x y : chainSetup.Elem}
    (h : chainSetup.le x y) :
    Chain3.rank x.1 ≤ Chain3.rank y.1 := by
  induction h with
  | refl => exact Nat.le_refl _
  | tail hab hbc ih =>
      exact Nat.le_trans ih (chain_cover_rank_mono hbc)

/-- Ambient-element form of rank monotonicity. -/
theorem chain_leOn_rank_mono {y x : Chain3}
    (h : chainSetup.leOn y x) :
    Chain3.rank y ≤ Chain3.rank x := by
  rcases h with ⟨hy, hx, hrel⟩
  exact chain_le_rank_mono hrel

/-- The empty set is a preorder order ideal of the functional chain. -/
theorem chain_empty_mem :
    (∅ : Finset Chain3) ∈ chainSetup.idealFamily := by
  rw [chainSetup.mem_idealFamily_iff]
  constructor
  · simp
  · intro x hx
    simp at hx

/-- `{a}` is a preorder order ideal of the functional chain. -/
theorem chain_singleton_a_mem :
    ({Chain3.a} : Finset Chain3) ∈ chainSetup.idealFamily := by
  rw [chainSetup.mem_idealFamily_iff]
  constructor
  · simp [Chain3.ground, chainSetup]
  · intro x hx y hy hle
    have hr := chain_leOn_rank_mono hle
    cases x <;> cases y <;> simp at hx ⊢ <;> norm_num [Chain3.rank] at hr

/-- `{a,b}` is a preorder order ideal of the functional chain. -/
theorem chainB_mem : chainB ∈ chainSetup.idealFamily := by
  rw [chainSetup.mem_idealFamily_iff]
  constructor
  · simp [chainB, Chain3.ground, chainSetup]
  · intro x hx y hy hle
    have hr := chain_leOn_rank_mono hle
    cases x <;> cases y <;> simp [chainB] at hx ⊢ <;> norm_num [Chain3.rank] at hr

/-- The full ground is a preorder order ideal. -/
theorem chain_ground_mem : Chain3.ground ∈ chainSetup.idealFamily := by
  rw [chainSetup.mem_idealFamily_iff]
  constructor
  · exact Finset.Subset.rfl
  · intro x hx y hy hle
    exact hy

/-- `a` reaches `b` in the functional preorder. -/
theorem chain_a_le_b : chainSetup.leOn Chain3.a Chain3.b := by
  refine ⟨by simp [chainSetup, Chain3.ground], by simp [chainSetup, Chain3.ground], ?_⟩
  apply Relation.ReflTransGen.single
  simp [FuncSetup.cover, chainSetup, Chain3.next, Chain3.rawNext]

/-- `b` reaches `c` in the functional preorder. -/
theorem chain_b_le_c : chainSetup.leOn Chain3.b Chain3.c := by
  refine ⟨by simp [chainSetup, Chain3.ground], by simp [chainSetup, Chain3.ground], ?_⟩
  apply Relation.ReflTransGen.single
  simp [FuncSetup.cover, chainSetup, Chain3.next, Chain3.rawNext]

/-- The decisive missing subset: `{b}` is not a preorder order ideal. -/
theorem chainA_not_mem : chainA ∉ chainSetup.idealFamily := by
  intro hA
  have hOrder := (chainSetup.mem_idealFamily_iff).mp hA
  have ha : Chain3.a ∈ chainA :=
    hOrder.2 (x := Chain3.b) (by simp [chainA])
      (y := Chain3.a) (by simp [chainSetup, Chain3.ground]) chain_a_le_b
  simpa [chainA] using ha

/-- Every preorder order ideal of the three-chain is one of the four expected
members. -/
theorem chain_orderIdeal_cases {I : Finset Chain3}
    (hI : chainSetup.IsOrderIdealOn I) :
    I = ∅ ∨ I = {Chain3.a} ∨ I = chainB ∨ I = Chain3.ground := by
  by_cases hc : Chain3.c ∈ I
  · have hb : Chain3.b ∈ I :=
      hI.2 hc (by simp [chainSetup, Chain3.ground]) chain_b_le_c
    have ha : Chain3.a ∈ I :=
      hI.2 hb (by simp [chainSetup, Chain3.ground]) chain_a_le_b
    right; right; right
    ext x
    cases x <;> simp [Chain3.ground, ha, hb, hc]
  · by_cases hb : Chain3.b ∈ I
    · have ha : Chain3.a ∈ I :=
        hI.2 hb (by simp [chainSetup, Chain3.ground]) chain_a_le_b
      right; right; left
      ext x
      cases x <;> simp [chainB, ha, hb, hc]
    · by_cases ha : Chain3.a ∈ I
      · right; left
        ext x
        cases x <;> simp [ha, hb, hc]
      · left
        ext x
        cases x <;> simp [ha, hb, hc]

/-- D002 exact fixture: the order ideals are exactly
`∅`, `{a}`, `{a,b}`, and `{a,b,c}`. -/
theorem chain_idealFamily_eq_expected :
    chainSetup.idealFamily = chainExpectedFamily := by
  classical
  ext I
  constructor
  · intro hI
    have hOrder := (chainSetup.mem_idealFamily_iff).mp hI
    rcases chain_orderIdeal_cases hOrder with h | h | h | h
    · subst I; simp [chainExpectedFamily]
    · subst I; simp [chainExpectedFamily]
    · subst I; simp [chainExpectedFamily]
    · subst I; simp [chainExpectedFamily]
  · intro hI
    simp only [chainExpectedFamily, Finset.mem_insert, Finset.mem_singleton] at hI
    rcases hI with h | h | h | h
    · subst I; exact chain_empty_mem
    · subst I; exact chain_singleton_a_mem
    · subst I; exact chainB_mem
    · subst I; exact chain_ground_mem

/-- D002 semantic obstruction: preorder-downward closure does not imply the
subset-downward `IsIdealFamilyOn` predicate. The proper member `{a,b}` has the
subset `{b}`, which is absent from the induced family. -/
theorem functional_three_chain_not_IsIdealFamilyOn :
    ¬ IsIdealFamilyOn chainSetup.idealFamily chainSetup.ground := by
  intro hIdeal
  have hBne : chainB ≠ chainSetup.ground := by
    intro hEq
    have hc : Chain3.c ∈ chainB := by
      rw [hEq]
      simp [chainSetup, Chain3.ground]
    simpa [chainB] using hc
  have hAB : chainA ⊆ chainB := by
    intro x hx
    simp [chainA] at hx
    subst x
    simp [chainB]
  have hA : chainA ∈ chainSetup.idealFamily :=
    hIdeal.2.2.2.2 chainB_mem hBne hAB
  exact chainA_not_mem hA

/-! ## D004: exact target and first proof-bearing semantic bridge -/

/-- Source-shaped normalized degree sum on a finite family and explicit ground.
This is the integer form used by the audited upstream theorem. -/
def NDSOn (F : Family α) (U : Finset α) : Int :=
  2 * (((F.sum fun S => S.card) : Nat) : Int) -
    (F.card : Int) * (U.card : Int)

/-- Functional-preorder NDS in the local source-shaped semantics. -/
noncomputable def FunctionalPreorderNDS (S : FuncSetup α) : Int :=
  NDSOn S.idealFamily S.ground

/-- NDS nonpositivity is exactly local average rarity; this closes the
normalization bridge and prevents an integer/Nat inequality drift. -/
theorem ndsOn_nonpos_iff_averageRareOn (F : Family α) (U : Finset α) :
    NDSOn F U ≤ 0 ↔ IsAverageRareOn F U := by
  unfold NDSOn IsAverageRareOn
  rw [Nat.mul_comm U.card F.card]
  omega

/-- The exact local D004 target. This is a proposition, not an assumed theorem. -/
def D004AverageRarityStatement (α : Type u) [DecidableEq α] : Prop :=
  ∀ (F : Family α) (U : Finset α),
    IsFunctionalPreorderIdealFamilyOn F U → IsAverageRareOn F U

/-- Exact source-shaped premise corresponding to the audited upstream
`main_nds_nonpos` theorem contract. It remains proof debt locally until the
upstream proof is semantically transported or reproved. -/
def SourceShapedMainNDSStatement (α : Type u) [DecidableEq α] : Prop :=
  ∀ S : FuncSetup α, FunctionalPreorderNDS S ≤ 0

/-- First substantive D004 bridge lemma: a local proof/transport of the exact
source-shaped NDS theorem discharges average rarity for the exact D003 class. -/
theorem sourceShapedMainNDS_implies_D004
    (hnds : SourceShapedMainNDSStatement α) :
    D004AverageRarityStatement α := by
  intro F U hFamily
  rcases hFamily with ⟨S, hU, hF⟩
  subst U
  subst F
  exact (ndsOn_nonpos_iff_averageRareOn S.idealFamily S.ground).mp (hnds S)

end MathSolve.UnionClosed.WP07
