import MathSolve.PNP.TM2ProgrammeRunStep
import MathSolve.PNP.TM2StackOps

/-!
# Proof-facing actions for mutating TM2 primitives

The concrete compiler defines `push` and `pop` actions inline.  This file gives
those actions stable names for the structural simulation proof and records the
generated-push stack recovery fact.
-/

namespace MathSolve.PNP

noncomputable section

/-- First Programme transition of a source `push`: move into the new stack cell. -/
def tm2PushMoveAction {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    (nextCode : TM2StatementCode source.tm) (state : source.tm.σ)
    (token : TM2ProvenanceToken source.tm)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm) :
    ProgrammeAction (TM2ProgrammeControl source) (TM2ProgrammeSymbol source.tm)
      (tm2WorkTapeCount source) where
  nextState := tm2ControlPushWrite source nextCode state token
  inputMove := .stay
  write := tm2PreserveWork source readWork
  workMove := tm2MoveSelected source k .left

/-- Single Programme transition implementing source `pop`. -/
def tm2PopAction {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    (nextCode : TM2StatementCode source.tm) (nextState : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm) :
    ProgrammeAction (TM2ProgrammeControl source) (TM2ProgrammeSymbol source.tm)
      (tm2WorkTapeCount source) where
  nextState := tm2ControlRun source nextCode nextState
  inputMove := .stay
  write := tm2WriteSelected source readWork k none
  workMove := tm2MoveSelected source k .right

/-- A provenance token generated by a coded push recovers that exact stack index. -/
theorem tm2PushTokenStack?_generated {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (k : source.tm.K) (valueFn : source.tm.σ → source.tm.Γ k)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.push k valueFn nextStmt) :
    tm2PushTokenStack? source (.inr (code, state)) = some k := by
  simp [tm2PushTokenStack?, hstmt]

/-- The inline compiler push branch is exactly the named push-move action. -/
theorem tm2RunAction_push {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (k : source.tm.K) (valueFn : source.tm.σ → source.tm.Γ k)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.push k valueFn nextStmt)
    (hnext : nextStmt ∈ Turing.TM2.stmts₁ code.2.1) :
    tm2RunAction source code state readWork =
      tm2PushMoveAction source k
        (tm2UnaryChildCode source code nextStmt hnext)
        state (.inr (code, state)) readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt hnext ⊢
  subst stmt
  simp [tm2RunAction, tm2PushMoveAction]

/-- The inline compiler pop branch is exactly the named pop action. -/
theorem tm2RunAction_pop {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (k : source.tm.K)
    (updateState : source.tm.σ → Option (source.tm.Γ k) → source.tm.σ)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.pop k updateState nextStmt)
    (hnext : nextStmt ∈ Turing.TM2.stmts₁ code.2.1) :
    tm2RunAction source code state readWork =
      tm2PopAction source k
        (tm2UnaryChildCode source code nextStmt hnext)
        (updateState state (tm2ReadSourceHead? source k readWork))
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt hnext ⊢
  subst stmt
  simp [tm2RunAction, tm2PopAction]

/-- The inline compiler peek branch is exactly the corresponding stay action. -/
theorem tm2RunAction_peek {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (k : source.tm.K)
    (updateState : source.tm.σ → Option (source.tm.Γ k) → source.tm.σ)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.peek k updateState nextStmt)
    (hnext : nextStmt ∈ Turing.TM2.stmts₁ code.2.1) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (tm2ControlRun source
          (tm2UnaryChildCode source code nextStmt hnext)
          (updateState state (tm2ReadSourceHead? source k readWork)))
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt hnext ⊢
  subst stmt
  simp [tm2RunAction]

/-- The inline compiler load branch is exactly the corresponding stay action. -/
theorem tm2RunAction_load {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (updateState : source.tm.σ → source.tm.σ)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.load updateState nextStmt)
    (hnext : nextStmt ∈ Turing.TM2.stmts₁ code.2.1) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (tm2ControlRun source
          (tm2UnaryChildCode source code nextStmt hnext)
          (updateState state))
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt hnext ⊢
  subst stmt
  simp [tm2RunAction]

/-- The compiler takes the true statement subtree when the branch predicate is true. -/
theorem tm2RunAction_branch_true {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (predicate : source.tm.σ → Bool)
    (trueStmt falseStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.branch predicate trueStmt falseStmt)
    (htrue : trueStmt ∈ Turing.TM2.stmts₁ code.2.1)
    (hp : predicate state = true) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (tm2ControlRun source
          (tm2UnaryChildCode source code trueStmt htrue) state)
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt htrue ⊢
  subst stmt
  simp [tm2RunAction, hp]

/-- The compiler takes the false statement subtree when the branch predicate is false. -/
theorem tm2RunAction_branch_false {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (predicate : source.tm.σ → Bool)
    (trueStmt falseStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.branch predicate trueStmt falseStmt)
    (hfalse : falseStmt ∈ Turing.TM2.stmts₁ code.2.1)
    (hp : predicate state = false) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (tm2ControlRun source
          (tm2UnaryChildCode source code falseStmt hfalse) state)
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt hfalse ⊢
  subst stmt
  have hp' : predicate state ≠ true := by
    simpa [hp]
  simp [tm2RunAction, hp']

/-- The inline compiler goto branch jumps to the root code selected by the source state. -/
theorem tm2RunAction_goto {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (nextLabel : source.tm.σ → source.tm.Λ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.goto nextLabel) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (tm2ControlRun source
          (TM2StatementCode.root source.tm (nextLabel state)) state)
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt ⊢
  subst stmt
  simp [tm2RunAction]

/-- The inline compiler halt branch selects the exact Programme terminal from
the represented output head. -/
theorem tm2RunAction_halt {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (readWork : Fin (tm2WorkTapeCount source) → TM2ProgrammeSymbol source.tm)
    (hstmt : code.2.1 = Turing.TM2.Stmt.halt) :
    tm2RunAction source code state readWork =
      tm2StayAction source
        (match tm2OutputBit? source readWork with
         | some true => tm2ControlAccept source
         | _ => tm2ControlReject source)
        readWork := by
  rcases code with ⟨label, ⟨stmt, hmem⟩⟩
  dsimp at hstmt ⊢
  subst stmt
  simp [tm2RunAction] <;> rfl

#print axioms tm2PushTokenStack?_generated
#print axioms tm2RunAction_push
#print axioms tm2RunAction_pop
#print axioms tm2RunAction_peek
#print axioms tm2RunAction_load
#print axioms tm2RunAction_branch_true
#print axioms tm2RunAction_branch_false
#print axioms tm2RunAction_goto
#print axioms tm2RunAction_halt

end

end MathSolve.PNP
