import MathSolve.PNP.TM2TokenDecode

/-!
# Elementary operations on represented TM2 stacks

These lemmas expose the head cell of the exact provenance-stack representation.
They are the local invariant facts used by the concrete Programme compiler for
`peek`, `pop`, and output inspection.
-/

namespace MathSolve.PNP

noncomputable section

/-- A token list denoting a nonempty source stack is itself nonempty, with a
head token denoting the source head value. -/
theorem TM2TokenListDenotes.exists_head {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    {tokens : List (TM2ProvenanceToken source.tm)}
    {value : source.tm.Γ k} {values : List (source.tm.Γ k)}
    (h : TM2TokenListDenotes source k tokens (value :: values)) :
    ∃ token rest,
      tokens = token :: rest ∧
      TM2TokenDenotes source k token value := by
  cases h with
  | cons hhead _ =>
      exact ⟨_, _, rfl, hhead⟩

/-- Removing the head of a valid nonempty token/source relation preserves
validity of the remaining stack. -/
theorem TM2TokenListDenotes.tail {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    {token : TM2ProvenanceToken source.tm}
    {tokens : List (TM2ProvenanceToken source.tm)}
    {value : source.tm.Γ k} {values : List (source.tm.Γ k)}
    (h : TM2TokenListDenotes source k (token :: tokens) (value :: values)) :
    TM2TokenListDenotes source k tokens values := by
  cases h with
  | cons _ htail => exact htail

/-- The provenance token generated by an accessible `push` statement denotes
exactly the symbol pushed by that statement at the recorded source state. -/
theorem tm2GeneratedPushToken_denotes {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (k : source.tm.K) (valueFn : source.tm.σ → source.tm.Γ k)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (hstmt : code.2.1 = Turing.TM2.Stmt.push k valueFn nextStmt) :
    TM2TokenDenotes source k (.inr (code, state)) (valueFn state) := by
  dsimp [TM2TokenDenotes]
  rw [hstmt]
  exact ⟨rfl, rfl⟩

/-- Consing the generated provenance token mirrors the source `push` exactly. -/
theorem TM2TokenListDenotes.push_generated {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (k : source.tm.K) (valueFn : source.tm.σ → source.tm.Γ k)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    {tokens : List (TM2ProvenanceToken source.tm)}
    {values : List (source.tm.Γ k)}
    (hstmt : code.2.1 = Turing.TM2.Stmt.push k valueFn nextStmt)
    (hrest : TM2TokenListDenotes source k tokens values) :
    TM2TokenListDenotes source k
      (.inr (code, state) :: tokens)
      (valueFn state :: values) := by
  exact .cons
    (tm2GeneratedPushToken_denotes source code state k valueFn nextStmt hstmt)
    hrest

/-- The exact embedding exposes the first provenance token at its designated head. -/
@[simp] theorem embedTM2TokenStack_head {tm : Turing.FinTM2}
    (token : TM2ProvenanceToken tm)
    (tokens : List (TM2ProvenanceToken tm)) (head : Int) :
    embedTM2TokenStack (token :: tokens) head head = some token := by
  simp [embedTM2TokenStack]

/-- The exact empty-stack embedding is blank at its designated head. -/
@[simp] theorem embedTM2TokenStack_empty_head {tm : Turing.FinTM2} (head : Int) :
    embedTM2TokenStack ([] : List (TM2ProvenanceToken tm)) head head = none := by
  simp [embedTM2TokenStack]

/-- A represented empty source stack is blank at the represented head. -/
theorem TM2StackRepresented.empty_head {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    (tape : Int → TM2ProgrammeSymbol source.tm) (head : Int)
    (h : TM2StackRepresented source k tape head []) :
    tape head = none := by
  rcases h with ⟨tokens, htokens, rfl⟩
  cases htokens
  simp

/-- A represented nonempty source stack exposes a provenance token whose
deterministic decoder is exactly the source head value. -/
theorem TM2StackRepresented.head_decode {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    (tape : Int → TM2ProgrammeSymbol source.tm) (head : Int)
    (value : source.tm.Γ k) (values : List (source.tm.Γ k))
    (h : TM2StackRepresented source k tape head (value :: values)) :
    ∃ token : TM2ProvenanceToken source.tm,
      tape head = some token ∧
      tm2TokenValue? source k token = some value := by
  rcases h with ⟨tokens, htokens, rfl⟩
  rcases TM2TokenListDenotes.exists_head source k htokens with
    ⟨token, rest, rfl, hhead⟩
  refine ⟨token, ?_, ?_⟩
  · simp
  · exact tm2TokenValue?_eq_some_of_denotes source k token value hhead


/-- Moving the represented head left by one and writing a new provenance token
is exactly the embedded representation of consing that token. -/
theorem embedTM2TokenStack_push {tm : Turing.FinTM2}
    (token : TM2ProvenanceToken tm)
    (tokens : List (TM2ProvenanceToken tm)) (head : Int) :
    Function.update (embedTM2TokenStack tokens head) (head - 1) (some token) =
      embedTM2TokenStack (token :: tokens) (head - 1) := by
  funext position
  rw [Function.update_apply]
  by_cases hpos : position = head - 1
  · subst position
    simp [embedTM2TokenStack]
  · simp only [hpos, if_false]
    simp [embedTM2TokenStack]
    split_ifs <;> try simp_all <;> omega

/-- Erasing the represented head of a nonempty stack and moving right by one
is exactly the embedded representation of the tail. -/
theorem embedTM2TokenStack_pop {tm : Turing.FinTM2}
    (token : TM2ProvenanceToken tm)
    (tokens : List (TM2ProvenanceToken tm)) (head : Int) :
    Function.update (embedTM2TokenStack (token :: tokens) head) head none =
      embedTM2TokenStack tokens (head + 1) := by
  funext position
  rw [Function.update_apply]
  by_cases hpos : position = head
  · subst position
    simp [embedTM2TokenStack]
  · simp only [hpos, if_false]
    simp [embedTM2TokenStack]
    split_ifs <;> try simp_all <;> omega

/-- The two-phase Programme push update preserves the exact source-stack
representation and adds the source value generated by the push statement. -/
theorem TM2StackRepresented.push_generated {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision)
    (code : TM2StatementCode source.tm) (state : source.tm.σ)
    (k : source.tm.K) (valueFn : source.tm.σ → source.tm.Γ k)
    (nextStmt : Turing.TM2.Stmt source.tm.Γ source.tm.Λ source.tm.σ)
    (tape : Int → TM2ProgrammeSymbol source.tm) (head : Int)
    (values : List (source.tm.Γ k))
    (hstmt : code.2.1 = Turing.TM2.Stmt.push k valueFn nextStmt)
    (hrep : TM2StackRepresented source k tape head values) :
    TM2StackRepresented source k
      (Function.update tape (head - 1) (some (.inr (code, state))))
      (head - 1) (valueFn state :: values) := by
  rcases hrep with ⟨tokens, htokens, rfl⟩
  refine ⟨.inr (code, state) :: tokens, ?_, ?_⟩
  · exact TM2TokenListDenotes.push_generated
      source code state k valueFn nextStmt hstmt htokens
  · exact embedTM2TokenStack_push (.inr (code, state)) tokens head

/-- The Programme pop update preserves exact representation of the source tail. -/
theorem TM2StackRepresented.pop {decision : List Bool → Bool}
    (source : ImportedTM2Witness decision) (k : source.tm.K)
    (tape : Int → TM2ProgrammeSymbol source.tm) (head : Int)
    (value : source.tm.Γ k) (values : List (source.tm.Γ k))
    (hrep : TM2StackRepresented source k tape head (value :: values)) :
    TM2StackRepresented source k
      (Function.update tape head none) (head + 1) values := by
  rcases hrep with ⟨tokens, htokens, rfl⟩
  cases htokens with
  | cons hhead htail =>
      refine ⟨_, htail, ?_⟩
      exact embedTM2TokenStack_pop _ _ head

#print axioms TM2TokenListDenotes.exists_head
#print axioms TM2TokenListDenotes.tail
#print axioms tm2GeneratedPushToken_denotes
#print axioms TM2TokenListDenotes.push_generated
#print axioms embedTM2TokenStack_head
#print axioms embedTM2TokenStack_empty_head
#print axioms TM2StackRepresented.empty_head
#print axioms TM2StackRepresented.head_decode
#print axioms embedTM2TokenStack_push
#print axioms embedTM2TokenStack_pop
#print axioms TM2StackRepresented.push_generated
#print axioms TM2StackRepresented.pop

end

end MathSolve.PNP
