name: GCL conformance
on:
  pull_request:
  push:
    branches: [main]
  merge_group:
  schedule:
    - cron: "37 7 * * 1"
permissions:
  contents: read
jobs:
  policy:
    uses: grandchallenge/.github/.github/workflows/gcl-policy.yml@6df9adc6fae6086eab11800dadd06af6dc0f3b5b
    with:
      profile: Solve
      standards_ref: c5604226b306a1b6fe104757a3852ded5cba2bb9
  security:
    permissions:
      contents: read
      security-events: write
    uses: grandchallenge/.github/.github/workflows/gcl-security.yml@6df9adc6fae6086eab11800dadd06af6dc0f3b5b
